version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Saigon
  open-pull-requests-limit: 10
  target-branch: dependency
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: typedoc
    versions:
    - 0.20.19
    - 0.20.20
    - 0.20.21
    - 0.20.22
    - 0.20.23
    - 0.20.24
    - 0.20.25
    - 0.20.26
    - 0.20.27
    - 0.20.28
    - 0.20.29
    - 0.20.30
    - 0.20.31
    - 0.20.32
    - 0.20.33
    - 0.20.34
    - 0.20.35
  - dependency-name: cspell
    versions:
    - 5.2.4
    - 5.3.0
    - 5.3.1
    - 5.3.10
    - 5.3.11
    - 5.3.2
    - 5.3.3
    - 5.3.4
    - 5.3.5
    - 5.3.6
    - 5.3.7
    - 5.3.8
    - 5.3.9
  - dependency-name: "@semantic-release/npm"
    versions:
    - 7.0.10
    - 7.1.0
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.3.8
    - 17.3.9
    - 17.4.0
    - 17.4.1
  - dependency-name: typescript
    versions:
    - 4.1.4
  - dependency-name: eslint-config-airbnb-typescript
    versions:
    - 12.0.1
    - 12.2.0
    - 12.3.0
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
